name: Despliegue de Servidor Streamlit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on local server
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stop existing container
      run: docker compose down || true

    - name: Build and run new container
      run: docker compose up -d --build

    # - name: Notify on Discord
    #   uses: Ilshidur/action-discord@master
    #   with:
    #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
    #     message: "🚀 FastAPI desplegado en servidor local tras merge en develop."

    # - name: Notify on Discord
    #   uses: Ilshidur/action-discord@master
    #   env:
    #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    #   with:
    #     args: "🚀 Nuevo commit en la rama `${{ github.ref_name }}` por ${{ github.actor }}: ${{ github.event.head_commit.message }}"